### ISSUE TITLE
[Improvement] OpenUPM

### ISSUE THREAD

**Issue by Xeoneid** [servicetitan/lazy-proxy-unity#9]
Hi! Thanks for sharing, this is very useful but Unity keeps messing with NuGet. I was wondering if there are any plans to create an OpenUPM package out of it. If now, would be ok if I create it?

**Comment by hypercodeplace** [comment]
Hi @Xeoneid 

This is a package for [Unity container](https://github.com/unitycontainer/unity) rather than for [Unity engine](https://unity.com/). Can you please confirm we are speaking about the same things.

**Comment by Xeoneid** [comment]
Sorry for not replying earlier, I was really busy.
My bad, I didn't know about Unity Container, I thought it was some kind of executing Unity Engine on a kind of Docker container.

Thanks for your reply
